import React, { useState, useEffect } from 'react';
import { 
  Search, 
  Calendar, 
  Plane, 
  CreditCard, 
  MessageCircle, 
  Mail, 
  ChevronDown, 
  ChevronUp, 
  ChevronRight 
} from 'lucide-react';
import { SharedBookingHeader } from './SharedBookingHeader';

interface Props {
  onBackToMyBookings: () => void;
  onOpenSignIn: () => void;
  onHomeClick: () => void;
}

export const Page12HelpContact: React.FC<Props> = ({
  onBackToMyBookings,
  onOpenSignIn,
  onHomeClick
}) => {
  const [searchQuery, setSearchQuery] = useState('');
  const [attachRef, setAttachRef] = useState('');
  const [openFaqIndex, setOpenFaqIndex] = useState<number | null>(null);
  const [liveFaqs, setLiveFaqs] = useState<{ q: string; a: string }[]>([]);

  useEffect(() => {
    const fetchFaqs = async () => {
      try {
        const res = await fetch('/api/v1/global-hub/help/faqs');
        if (res.ok) {
          const data = await res.json();
          if (data.faqs && data.faqs.length > 0) {
            setLiveFaqs(data.faqs.map((f: any) => ({
              q: f.question,
              a: f.answer
            })));
          }
        }
      } catch (err) {
        console.warn('FAQ sync notice:', err);
      }
    };
    fetchFaqs();
  }, []);

  const defaultFaqs = [
    {
      q: 'How do I change my booking?',
      a: 'You can modify your pickup time, meeting point, or passenger details for free up to 24 hours before scheduled pickup directly from your My Bookings dashboard.'
    },
    {
      q: 'Where will I meet my chauffeur at the airport?',
      a: 'For airport arrivals, your chauffeur will meet you inside the terminal baggage claim area holding a digital name sign, or at curbside express pickup depending on your preference.'
    },
    {
      q: 'What payment methods do you accept?',
      a: 'We accept all major credit and debit cards (Visa, MasterCard, American Express, Discover) as well as Apple Pay. All transactions are securely pre-authorized with zero raw card storage.'
    },
    {
      q: 'Can I get a receipt for my ride?',
      a: 'Yes, a single unified invoice receipt is automatically generated by Global Hub and can be viewed, downloaded, or printed directly from the confirmation screen or My Bookings.'
    }
  ];

  const faqs = liveFaqs.length > 0 ? liveFaqs : defaultFaqs;


  return (
    <div style={{ minHeight: '100vh', background: '#FFFFFF', color: '#111827', display: 'flex', flexDirection: 'column', fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif' }}>
      <SharedBookingHeader
        onOpenMyBookings={onBackToMyBookings}
        onOpenSignIn={onOpenSignIn}
        onHomeClick={onHomeClick}
      />

      <div style={{ maxWidth: '1040px', margin: '0 auto', width: '100%', padding: '40px 24px 60px 24px', flex: 1 }}>
        {/* Title + Search Box */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '28px', flexWrap: 'wrap', gap: '16px' }}>
          <h1 style={{ fontSize: '36px', fontWeight: '900', color: '#000000', letterSpacing: '-0.03em', margin: 0 }}>
            How can we help?
          </h1>

          <div style={{ position: 'relative', width: '280px' }}>
            <Search size={16} color="#9CA3AF" style={{ position: 'absolute', left: '12px', top: '12px' }} />
            <input
              type="text"
              placeholder="Search help"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              style={{
                width: '100%',
                padding: '10px 14px 10px 36px',
                borderRadius: '8px',
                border: '1px solid #D1D5DB',
                fontSize: '13px',
                outline: 'none',
                boxSizing: 'border-box'
              }}
            />
          </div>
        </div>

        {/* 3 Main Category Cards */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '16px', marginBottom: '32px' }}>
          <div style={{
            background: '#FFFFFF',
            border: '1px solid #E5E7EB',
            borderRadius: '12px',
            padding: '20px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            cursor: 'pointer'
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
              <div style={{ width: '40px', height: '40px', borderRadius: '8px', background: '#F3F4F6', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <Calendar size={20} color="#1D68FE" />
              </div>
              <div>
                <div style={{ fontSize: '14px', fontWeight: '700', color: '#000000' }}>Booking changes</div>
                <div style={{ fontSize: '12px', color: '#6B7280', marginTop: '2px' }}>Modify or cancel your ride</div>
              </div>
            </div>
            <ChevronRight size={18} color="#9CA3AF" />
          </div>

          <div style={{
            background: '#FFFFFF',
            border: '1px solid #E5E7EB',
            borderRadius: '12px',
            padding: '20px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            cursor: 'pointer'
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
              <div style={{ width: '40px', height: '40px', borderRadius: '8px', background: '#F3F4F6', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <Plane size={20} color="#1D68FE" />
              </div>
              <div>
                <div style={{ fontSize: '14px', fontWeight: '700', color: '#000000' }}>Airport pickup</div>
                <div style={{ fontSize: '12px', color: '#6B7280', marginTop: '2px' }}>Meet and greet, terminals, etc.</div>
              </div>
            </div>
            <ChevronRight size={18} color="#9CA3AF" />
          </div>

          <div style={{
            background: '#FFFFFF',
            border: '1px solid #E5E7EB',
            borderRadius: '12px',
            padding: '20px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            cursor: 'pointer'
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
              <div style={{ width: '40px', height: '40px', borderRadius: '8px', background: '#F3F4F6', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <CreditCard size={20} color="#1D68FE" />
              </div>
              <div>
                <div style={{ fontSize: '14px', fontWeight: '700', color: '#000000' }}>Payments & receipts</div>
                <div style={{ fontSize: '12px', color: '#6B7280', marginTop: '2px' }}>Invoices and payment methods</div>
              </div>
            </div>
            <ChevronRight size={18} color="#9CA3AF" />
          </div>
        </div>

        {/* Need a hand? Support Section */}
        <div style={{
          background: '#F9FAFB',
          border: '1px solid #E5E7EB',
          borderRadius: '12px',
          padding: '24px',
          marginBottom: '36px',
          display: 'grid',
          gridTemplateColumns: '1.2fr 1fr',
          gap: '24px',
          alignItems: 'center'
        }}>
          <div>
            <h3 style={{ fontSize: '16px', fontWeight: '800', color: '#000000', margin: '0 0 4px 0' }}>
              Need a hand?
            </h3>
            <p style={{ fontSize: '13px', color: '#6B7280', margin: '0 0 16px 0' }}>
              Our dedicated 24/7 concierge team is here to help.
            </p>

            <div style={{ display: 'flex', gap: '12px' }}>
              <button
                onClick={() => alert('Live support chat connected with concierge agent.')}
                style={{
                  background: '#1D68FE',
                  color: '#FFFFFF',
                  border: 'none',
                  borderRadius: '8px',
                  padding: '10px 18px',
                  fontSize: '13px',
                  fontWeight: '700',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px'
                }}
              >
                <MessageCircle size={14} /> Chat with support
              </button>

              <button
                onClick={() => alert('Support email opened: support@limo.com')}
                style={{
                  background: '#FFFFFF',
                  color: '#111827',
                  border: '1px solid #D1D5DB',
                  borderRadius: '8px',
                  padding: '10px 16px',
                  fontSize: '13px',
                  fontWeight: '600',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px'
                }}
              >
                <Mail size={14} /> Contact us
              </button>
            </div>
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '12px', fontWeight: '600', color: '#374151', marginBottom: '6px' }}>
              Attach a booking <span style={{ fontWeight: '400', color: '#6B7280' }}>(optional)</span>
            </label>
            <input
              type="text"
              placeholder="e.g. LM-20481"
              value={attachRef}
              onChange={(e) => setAttachRef(e.target.value)}
              style={{ width: '100%', padding: '10px 12px', borderRadius: '8px', border: '1px solid #D1D5DB', fontSize: '13px', outline: 'none', boxSizing: 'border-box' }}
            />
            <span style={{ fontSize: '11px', color: '#6B7280', marginTop: '4px', display: 'block' }}>
              This helps us find your trip faster.
            </span>
          </div>
        </div>

        {/* Popular Questions Accordion */}
        <div>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '14px' }}>
            <h3 style={{ fontSize: '16px', fontWeight: '800', color: '#000000', margin: 0 }}>
              Popular questions
            </h3>
            <span style={{ fontSize: '12px', fontWeight: '600', color: '#1D68FE', cursor: 'pointer' }}>
              View all
            </span>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', borderTop: '1px solid #E5E7EB' }}>
            {faqs.map((faq, idx) => {
              const isOpen = openFaqIndex === idx;
              return (
                <div key={idx} style={{ borderBottom: '1px solid #E5E7EB', padding: '14px 0' }}>
                  <div
                    onClick={() => setOpenFaqIndex(isOpen ? null : idx)}
                    style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', cursor: 'pointer' }}
                  >
                    <span style={{ fontSize: '14px', fontWeight: '600', color: '#111827' }}>
                      {faq.q}
                    </span>
                    {isOpen ? <ChevronUp size={16} color="#6B7280" /> : <ChevronDown size={16} color="#6B7280" />}
                  </div>
                  {isOpen && (
                    <div style={{ marginTop: '8px', fontSize: '13px', color: '#6B7280', lineHeight: '1.5' }}>
                      {faq.a}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer style={{
        height: '60px',
        background: '#FFFFFF',
        borderTop: '1px solid #E5E7EB',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '0 40px',
        fontSize: '12px',
        color: '#6B7280',
        marginTop: 'auto'
      }}>
        <div style={{ display: 'flex', gap: '20px' }}>
          <a href="#help" style={{ color: '#6B7280', textDecoration: 'none' }}>Help</a>
          <a href="#contact" style={{ color: '#6B7280', textDecoration: 'none' }}>Contact</a>
          <a href="#terms" style={{ color: '#6B7280', textDecoration: 'none' }}>Terms</a>
          <a href="#privacy" style={{ color: '#6B7280', textDecoration: 'none' }}>Privacy</a>
        </div>
        <div style={{ fontSize: '11px', fontWeight: '800', letterSpacing: '0.08em', color: '#111827' }}>
          RIDE FURTHER
        </div>
      </footer>
    </div>
  );
};
