"""
SQLAlchemy ORM Database Models for Global Hub Marketplace & Clearinghouse.
Covers:
- Public Multi-City & Single-Trip Bookings with Reference Codes (e.g. LM-20481)
- Single Unified Customer Invoices (Merchant of Record)
- Verified Local Affiliate Vendor Profiles & Fleets (Airline-Style Comparison)
- Autonomous Sourcing RFPs & Round-Robin Queue
- Stripe Connect 80/10/10 Multi-Party Clearinghouse Settlements
- Real-Time Chauffeur GPS Telemetry & Flight Tracking (Page 11 Radar)
- Audit & Financial Double-Entry Logging
"""

import uuid
from datetime import datetime, timezone
from decimal import Decimal
from sqlalchemy import (
    Column, String, Integer, Float, Boolean, DateTime, Text, ForeignKey, Numeric
)
from sqlalchemy.orm import relationship
from packages.shared.database import Base


class HubMasterBookingModel(Base):
    """Authoritative Customer Booking (One-Way, Hourly, or Multi-City) with Unified Reference."""
    __tablename__ = "hub_master_bookings"

    booking_id = Column(String(64), primary_key=True, default=lambda: f"bk-{uuid.uuid4().hex[:8]}")
    booking_reference = Column(String(32), unique=True, index=True, nullable=False) # e.g. LM-20481
    trip_type = Column(String(32), default="ONE_WAY") # ONE_WAY, HOURLY, MULTI_CITY
    status = Column(String(32), default="CONFIRMED", index=True) # CONFIRMED, CHAUFFEUR_DISPATCHED, IN_PROGRESS, COMPLETED, CANCELLED
    
    # Customer / Passenger Information
    passenger_type = Column(String(16), default="MYSELF") # MYSELF, SOMEONE_ELSE
    passenger_first_name = Column(String(64), nullable=False)
    passenger_last_name = Column(String(64), nullable=False)
    passenger_email = Column(String(128), nullable=False, index=True)
    passenger_phone = Column(String(32), nullable=False)
    booker_email = Column(String(128), nullable=True)
    
    # Trip Locations & Schedule
    pickup_address = Column(String(255), nullable=False)
    dropoff_address = Column(String(255), nullable=False)
    pickup_datetime_str = Column(String(64), nullable=False)
    passengers_count = Column(Integer, default=2)
    
    # Airport & Special Service Details
    flight_number = Column(String(32), nullable=True)
    pickup_meeting_point = Column(String(128), default="JFK Airport - Arrivals (Baggage Claim)")
    child_seats_count = Column(Integer, default=0)
    special_requests = Column(Text, nullable=True)
    
    # Financial Totals (Unified Customer Charge)
    vehicle_class = Column(String(64), default="BUSINESS_CLASS")
    vehicle_model_name = Column(String(128), default="Mercedes-Benz S-Class or similar")
    base_fare_usd = Column(Numeric(10, 2), default=Decimal("125.00"))
    fees_and_taxes_usd = Column(Numeric(10, 2), default=Decimal("20.00"))
    total_amount_usd = Column(Numeric(10, 2), default=Decimal("145.00"))
    payment_method = Column(String(32), default="CARD")
    stripe_payment_intent_id = Column(String(128), nullable=True)
    
    # Sourcing & Vendor Mode
    sourcing_mode = Column(String(32), default="AUTO_ROUTED")
    assigned_vendor_id = Column(String(64), nullable=True)
    assigned_vendor_name = Column(String(128), nullable=True)
    assigned_chauffeur_name = Column(String(128), default="Alex")
    assigned_chauffeur_phone = Column(String(32), default="+1 (212) 555-0199")
    assigned_vehicle_plate = Column(String(32), default="NYC 7264")
    
    # Timestamp Tracking
    pickup_datetime_utc = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    legs = relationship("HubLegModel", back_populates="booking", cascade="all, delete-orphan")
    invoice = relationship("HubInvoiceModel", uselist=False, back_populates="booking", cascade="all, delete-orphan")
    settlement = relationship("HubEscrowSettlementModel", uselist=False, back_populates="booking", cascade="all, delete-orphan")
    telemetry = relationship("HubDriverTelemetryModel", uselist=False, back_populates="booking", cascade="all, delete-orphan")


class HubInvoiceModel(Base):
    """Single Unified Customer Invoice generated by Global Hub (Merchant of Record)."""
    __tablename__ = "hub_unified_invoices"

    invoice_id = Column(String(64), primary_key=True, default=lambda: f"inv-{uuid.uuid4().hex[:8]}")
    invoice_number = Column(String(32), unique=True, index=True, nullable=False) # e.g. INV-GH-2026-9041
    booking_id = Column(String(64), ForeignKey("hub_master_bookings.booking_id"), nullable=False, index=True)
    customer_name = Column(String(128), nullable=False)
    customer_email = Column(String(128), nullable=False)
    
    subtotal_usd = Column(Numeric(10, 2), nullable=False)
    taxes_usd = Column(Numeric(10, 2), nullable=False)
    gratuity_usd = Column(Numeric(10, 2), default=Decimal("0.00"))
    total_charged_usd = Column(Numeric(10, 2), nullable=False)
    currency = Column(String(8), default="USD")
    payment_status = Column(String(32), default="PAID")
    issued_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    booking = relationship("HubMasterBookingModel", back_populates="invoice")


class HubDriverTelemetryModel(Base):
    """Real-Time GPS Telemetry & Live Chauffeur Radar Tracking (Page 11)."""
    __tablename__ = "hub_driver_telemetry"

    telemetry_id = Column(String(64), primary_key=True, default=lambda: f"tel-{uuid.uuid4().hex[:8]}")
    booking_id = Column(String(64), ForeignKey("hub_master_bookings.booking_id"), unique=True, nullable=False, index=True)
    chauffeur_name = Column(String(128), default="Alex")
    chauffeur_rating = Column(Numeric(3, 2), default=Decimal("4.92"))
    total_rides = Column(Integer, default=320)
    vehicle_plate = Column(String(32), default="NYC 7264")
    vehicle_name = Column(String(128), default="Mercedes-Benz S-Class")
    
    current_lat = Column(Float, default=40.7128)
    current_lng = Column(Float, default=-74.0060)
    heading_deg = Column(Float, default=45.0)
    speed_mph = Column(Float, default=28.5)
    eta_minutes = Column(Integer, default=8)
    status_text = Column(String(128), default="Chauffeur assigned - Your chauffeur is on the way.")
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    booking = relationship("HubMasterBookingModel", back_populates="telemetry")


class HubVendorProfileModel(Base):
    """Verified Local Affiliate Vendor Profiles & Fleet Inventory (Airline-Style Comparison)."""
    __tablename__ = "hub_vendor_profiles"

    vendor_id = Column(String(64), primary_key=True, default=lambda: f"vnd-{uuid.uuid4().hex[:8]}")
    company_name = Column(String(128), nullable=False)
    market_city = Column(String(64), nullable=False, index=True)
    airport_corridors_json = Column(Text, default="[]")
    rating_score = Column(Numeric(3, 2), default=Decimal("4.96"))
    total_reviews_count = Column(Integer, default=2180)
    fleet_size = Column(Integer, default=28)
    
    vehicle_makes = Column(String(255), default="Mercedes-Benz S580, Cadillac Escalade ESV, BMW 760i")
    amenities_json = Column(Text, default='["Free High-Speed Wi-Fi", "Inside Baggage Claim Meet & Greet", "Fiji Water & Mints", "Live Radar Tracking"]')
    cancellation_policy = Column(String(128), default="Free cancellation up to 24 hours before pickup")
    
    business_class_base_rate_usd = Column(Numeric(10, 2), default=Decimal("125.00"))
    first_class_base_rate_usd = Column(Numeric(10, 2), default=Decimal("185.00"))
    business_van_base_rate_usd = Column(Numeric(10, 2), default=Decimal("165.00"))
    
    stripe_connect_account_id = Column(String(128), nullable=True)
    is_active = Column(Boolean, default=True)
    is_vetted_partner = Column(Boolean, default=True)
    round_robin_weight = Column(Integer, default=100)
    health_status = Column(String(32), default="ONLINE_HEALTHY", index=True) # ONLINE_HEALTHY, DEGRADED, OFFLINE
    api_endpoint_url = Column(String(255), default="http://localhost:8001")
    base_latitude = Column(Float, default=39.9526)
    base_longitude = Column(Float, default=-75.1652)
    operating_radius_miles = Column(Float, default=150.0)
    primary_chauffeur_name = Column(String(128), default="Marcus Vance")
    primary_chauffeur_phone = Column(String(32), default="+1 (215) 555-0144")
    primary_vehicle_plate = Column(String(32), default="PA 8492-LM")
    primary_vehicle_name = Column(String(128), default="Lincoln Navigator L")
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class HubItineraryModel(Base):
    """Global Master Multi-Leg Itinerary spanning multiple cities."""
    __tablename__ = "hub_master_itineraries"

    itinerary_id = Column(String(64), primary_key=True, default=lambda: f"itin-{uuid.uuid4().hex[:8]}")
    title = Column(String(255), nullable=False)
    total_legs_count = Column(Integer, default=1)
    cities_spanned_json = Column(Text, default="[]")
    subtotal_net_usd = Column(Numeric(10, 2), default=Decimal("0.00"))
    all_inclusive_total_usd = Column(Numeric(10, 2), default=Decimal("0.00"))
    is_partially_priced = Column(Boolean, default=False)
    pending_legs_count = Column(Integer, default=0)
    status = Column(String(32), default="DRAFT", index=True)
    customer_name = Column(String(128), nullable=True)
    customer_email = Column(String(128), nullable=True)
    customer_phone = Column(String(32), nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)

    legs = relationship("HubLegModel", back_populates="itinerary", cascade="all, delete-orphan")
    rfps = relationship("HubRFPModel", back_populates="itinerary", cascade="all, delete-orphan")


class HubLegModel(Base):
    """Individual Itinerary Leg with Geo-Region Allocation."""
    __tablename__ = "hub_itinerary_legs"

    leg_id = Column(String(64), primary_key=True, default=lambda: f"leg-{uuid.uuid4().hex[:8]}")
    itinerary_id = Column(String(64), ForeignKey("hub_master_itineraries.itinerary_id"), nullable=True, index=True)
    booking_id = Column(String(64), ForeignKey("hub_master_bookings.booking_id"), nullable=True, index=True)
    leg_index = Column(Integer, default=0)
    title = Column(String(255), nullable=False)
    origin_city = Column(String(64), nullable=False, index=True)
    origin_address = Column(String(255), nullable=False)
    destination_city = Column(String(64), nullable=False, index=True)
    destination_address = Column(String(255), nullable=False)
    distance_miles = Column(Numeric(10, 2), default=Decimal("15.00"))
    vehicle_class = Column(String(64), default="BUSINESS_CLASS")
    total_leg_amount_usd = Column(Numeric(10, 2), default=Decimal("0.00"))
    price_status = Column(String(64), default="LOCKED_IN_NETWORK", index=True)
    allocated_hub_node_id = Column(String(64), default="hub-us-east-prod")
    servicing_vendor_id = Column(String(64), nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    itinerary = relationship("HubItineraryModel", back_populates="legs")
    booking = relationship("HubMasterBookingModel", back_populates="legs")


class HubRFPModel(Base):
    """Autonomous Reverse Auction RFP for Out-of-Market Sourcing."""
    __tablename__ = "hub_sourcing_rfps"

    rfp_id = Column(String(64), primary_key=True, default=lambda: f"rfp-{uuid.uuid4().hex[:8]}")
    itinerary_id = Column(String(64), ForeignKey("hub_master_itineraries.itinerary_id"), nullable=False, index=True)
    leg_id = Column(String(64), nullable=False, index=True)
    target_city = Column(String(64), nullable=False, index=True)
    target_vendor_name = Column(String(128), nullable=False)
    target_vendor_email = Column(String(128), nullable=False)
    target_vendor_phone = Column(String(32), nullable=True)
    pickup_address = Column(String(255), nullable=False)
    dropoff_address = Column(String(255), nullable=False)
    pickup_time_utc = Column(DateTime, nullable=False)
    vehicle_class = Column(String(64), default="BUSINESS_CLASS")
    benchmark_payout_usd = Column(Numeric(10, 2), default=Decimal("185.00"))
    quoted_rate_usd = Column(Numeric(10, 2), nullable=True)
    status = Column(String(64), default="AI_DISPATCHED", index=True)
    quote_token = Column(String(64), unique=True, index=True)
    sent_at_utc = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    escalation_deadline_utc = Column(DateTime, nullable=False)

    itinerary = relationship("HubItineraryModel", back_populates="rfps")


class HubEscrowSettlementModel(Base):
    """Stripe Connect 80/10/10 Multi-Party Clearinghouse Settlement."""
    __tablename__ = "hub_escrow_settlements"

    settlement_id = Column(String(64), primary_key=True, default=lambda: f"stl-{uuid.uuid4().hex[:8]}")
    itinerary_id = Column(String(64), ForeignKey("hub_master_itineraries.itinerary_id"), nullable=True, index=True)
    booking_id = Column(String(64), ForeignKey("hub_master_bookings.booking_id"), nullable=True, index=True)
    total_fare_usd = Column(Numeric(10, 2), nullable=False)
    servicing_payout_usd = Column(Numeric(10, 2), nullable=False) # 80%
    originating_commission_usd = Column(Numeric(10, 2), nullable=False) # 10%
    platform_clearing_fee_usd = Column(Numeric(10, 2), nullable=False) # 10%
    servicing_vendor_id = Column(String(64), nullable=False, index=True)
    originating_vendor_id = Column(String(64), nullable=False, index=True)
    stripe_payment_intent_id = Column(String(128), nullable=True)
    stripe_transfer_servicing_id = Column(String(128), nullable=True)
    status = Column(String(32), default="PREAUTH_HELD", index=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    booking = relationship("HubMasterBookingModel", back_populates="settlement")


class HubClearinghouseConfigModel(Base):
    """Dynamic In-App Clearinghouse Split, Pricing Multipliers & Marketplace Operational Rules."""
    __tablename__ = "hub_clearinghouse_config"

    config_id = Column(String(64), primary_key=True, default="global_clearinghouse_master")
    servicing_affiliate_payout_pct = Column(Numeric(5, 2), default=Decimal("80.00"))
    originating_booker_commission_pct = Column(Numeric(5, 2), default=Decimal("10.00"))
    platform_clearing_fee_pct = Column(Numeric(5, 2), default=Decimal("10.00"))
    escrow_hold_buffer_hours = Column(Integer, default=24)
    intermediate_stop_fee_usd = Column(Numeric(10, 2), default=Decimal("15.00"))
    airport_terminal_fee_usd = Column(Numeric(10, 2), default=Decimal("20.00"))
    min_hourly_duration_hours = Column(Integer, default=2)
    hourly_business_rate_usd = Column(Numeric(10, 2), default=Decimal("45.00"))
    hourly_first_rate_usd = Column(Numeric(10, 2), default=Decimal("70.00"))
    hourly_van_rate_usd = Column(Numeric(10, 2), default=Decimal("60.00"))
    surge_multiplier = Column(Numeric(4, 2), default=Decimal("1.00"))
    tax_percentage = Column(Numeric(5, 2), default=Decimal("15.00"))
    free_cancellation_hours = Column(Integer, default=24)
    stripe_connect_master_platform_id = Column(String(128), nullable=True)
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

